apiVersion: apps/v1
kind: Service
metadata:
  name: way-be-memberservice
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: 'false'
    loadbalancer.ike.kakaocloud.com/load-balancer-type: 'NLB'
spec:
  selector:
    app: way-be-memberservice
  type: LoadBalancer
  ports:
    - name: http
      port: 50004
      targetPort: 8080