apiVersion: apps/v1
kind: Deployment
metadata:
  name: way-be-memberservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: way-be-memberservice
  template:
    metadata:
      labels:
        app: way-be-memberservice
    spec:
      nodeSelector:
        area: private
      containers:
        - name: way-memberservice-container
          image: gcu-dto-dev.kr-central-2.kcr.dev/way-member/way-member:1284fb4bdb8d75a1d1498877de1ba80e730e6dc6
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: way-be-memberservice-config
            - secretRef:
                name: way-be-memberservice-secret
      imagePullSecrets:
        - name: way-member-regi-sec
