apiVersion: apps/v1
kind: Deployment
metadata:
  name: way-be-memberservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: way-be-memberservice
  template:
    metadata:
      labels:
        app: way-be-memberservice
    spec:
      nodeSelector:
        area: private
      containers:
        - name: way-memberservice-container
          image: gcu-dto-dev.kr-central-2.kcr.dev/way-member/way-member:df6a9e342a379d92eeb02a4ecd1aed31cdf8cb9a
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: way-be-memberservice-config
            - secretRef:
                name: way-be-memberservice-secret
      imagePullSecrets:
        - name: way-member-regi-sec
