apiVersion: apps/v1
kind: Deployment
metadata:
  name: way-be-memberservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: way-be-memberservice
  template:
    metadata:
      labels:
        app: way-be-memberservice
    spec:
      nodeSelector:
        area: private
      containers:
        - name: way-memberservice-container
          image: gcu-dto-dev.kr-central-2.kcr.dev/way-member/way-member:334b93f001d4017032df107b0ae94c0d056e0a76
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: way-be-memberservice-config
            - secretRef:
                name: way-be-memberservice-secret
      imagePullSecrets:
        - name: way-member-regi-sec
---
apiVersion: apps/v1
kind: Service
metadata:
  name: member-service
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: 'false'
    loadbalancer.ike.kakaocloud.com/load-balancer-type: 'NLB'
spec:
  selector:
    app: way-be-memberservice
  type: LoadBalancer
  ports:
    - name: http
      port: 50004
      targetPort: 8080
  template:
    spec:
      containers:
        - image: gcu-dto-dev.kr-central-2.kcr.dev/way-member/way-member:334b93f001d4017032df107b0ae94c0d056e0a76
